# THESE ARE SUPPORTED FUNDING MODEL PLATFORMS

GITHUB: # REPLACE WITH UP TO 4 GITHUB SPONSORS-ENABLED USERNAMES E.G., [USER1, USER2]
PATREON: # REPLACE WITH A SINGLE PATREON USERNAME
OPEN_COLLECTIVE: # REPLACE WITH A SINGLE OPEN COLLECTIVE USERNAME
KO_FI: # REPLACE WITH A SINGLE KO-FI USERNAME
TIDELIFT: # REPLACE WITH A SINGLE TIDELIFT PLATFORM-NAME/PACKAGE-NAME E.G., NPM/BABEL
COMMUNITY_BRIDGE: # REPLACE WITH A SINGLE COMMUNITY BRIDGE PROJECT-NAME E.G., CLOUD-FOUNDRY
LIBERAPAY: # REPLACE WITH A SINGLE LIBERAPAY USERNAME
ISSUEHUNT: # REPLACE WITH A SINGLE ISSUEHUNT USERNAME
LFX_CROWDFUNDING: # REPLACE WITH A SINGLE LFX CROWDFUNDING PROJECT-NAME E.G., CLOUD-FOUNDRY
POLAR: # REPLACE WITH A SINGLE POLAR USERNAME

BUY_ME_A_COFFEE: # REPLACE WITH A SINGLE BUY ME A COFFEE USERNAME
THANKS_DEV: # REPLACE WITH A SINGLE THANKS.DEV USERNAME
CUSTOM: # REPLACE WITH UP TO 4 CUSTOM SPONSORSHIP URLS E.G., ['LINK1', 'LINK2']
